FROM node:20-alpine AS BUILDER
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . . 
RUN npm run build 

FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=BUILDER /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
